# 강의 노트
### Numpy 연습하기

In [4]:
import numpy as np

In [57]:
# 리스트 데이터를 배열로 바꾸기

list_data = [1,2,3]
array = np.array(list_data)

print(array.size)
print(array.dtype)
print(array[2])

print(list_data)
print(array)

3
int32
3
[1, 2, 3]
[1 2 3]


In [58]:
#리스트와 배열의 차이 (리스트를 곱해보자 !)

list_data *= 3
array *= 3

print(list_data)
print(array)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [60]:
# 0 부터 3까지의 배열 만들기

array1 = np.arange(4)      #range 배열버전.
print(array1)

# 0으로만 이루어진 배열 만들기

array2 = np.zeros((4,4), dtype=float)
print(array2)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [61]:
# 1로 이루어진 배열을 글자형태로 만들기

array3 = np.ones((3,3), dtype = 'str')
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [62]:
# 0~9까지 랜덤한 값의 배열 생성

array4 = np.random.randint(0,10, (3,3))
print(array4)

[[7 3 5]
 [0 8 8]
 [3 0 1]]


In [63]:
# 평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열 

array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[[ 0.98689922  0.19718704 -0.00449534]
 [-0.01236614  1.31426951 -1.17793907]
 [-0.52652881  0.6749429   0.34759479]]


In [64]:
#배열 가로 축 합치기

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)


(6,)
[1 2 3 4 5 6]


In [66]:
#배열 형태 바꾸기

array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape(2, 2)

print(array1)
print(array2)

[1 2 3 4]
[[1 2]
 [3 4]]


In [69]:
# 배열 세로축으로 합치기

array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)

print(array1)
print(array2)

array3 = np.concatenate([array1, array2], axis = 0)
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


### axis 0은 1차원은로 vector단위(행)을 설정하고 (행개념의 x축 개념)
### axis 1은 2차원으로 matrix 단위(행렬)을 정의하며 (열이라는 개념이 추가됨.y축 개념)
### axis 2는 3차원으로 tensor 라고 표현한다. (z축 개념.)

In [79]:
# 배열 나누기

array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis= 1)
print(left.shape)
print(right.shape)
print(left)

(2, 2)
(2, 2)
[[0 1]
 [4 5]]
